<a href="https://colab.research.google.com/github/rizqunaali/bitcoin_stock_data/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BIGDATA Kumpulan Data Harga Bitcoin
# Nama : muhammad rizquna ali akbar, Nim : 24.11.6095
# Nama : Bryan Anarki, Nim : 24.11.6080

In [49]:
# Import library
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# cara 1 : Upload Dataset dari lokal computer

In [50]:
# Cara 1: Upload Dataset dari lokal komputer
from google.colab import files
upload = files.upload()

Saving bitcoin_stock_data.csv to bitcoin_stock_data.csv

In [51]:
# Membaca dataset yang diunggah dari lokal
df_lokal = pd.read_csv("bitcoin_stock_data.csv") # Sesuaikan nama file jika berbeda
df_lokal.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
5,2014-09-22,399.100006,406.915985,397.130005,402.152008,402.152008,24127600
6,2014-09-23,402.091003,441.557007,396.196014,435.790985,435.790985,40739600
7,2014-09-24,435.897003,436.174011,419.204010,424.393005,424.393005,26268600
8,2014-09-25,424.017014,425.001007,400.802002,404.424988,404.424988,27491400
9,2014-09-26,403.946014,408.324005,395.546997,399.518005,399.518005,22882400

#2.uploade dataset dari google drive

In [52]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [53]:
# Ganti 'dataset' dengan nama folder asli yang Anda buat di Google Drive
path_drive = "/content/drive/MyDrive/fg/bitcoin_stock_data.csv"

df_drive = pd.read_csv(path_drive)
df_drive.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
5,2014-09-22,399.100006,406.915985,397.130005,402.152008,402.152008,24127600
6,2014-09-23,402.091003,441.557007,396.196014,435.790985,435.790985,40739600
7,2014-09-24,435.897003,436.174011,419.204010,424.393005,424.393005,26268600
8,2014-09-25,424.017014,425.001007,400.802002,404.424988,404.424988,27491400
9,2014-09-26,403.946014,408.324005,395.546997,399.518005,399.518005,22882400

In [54]:
# To find the correct path, you can list the contents of your Google Drive.
# For example, to list the contents of your 'MyDrive' folder:
!ls /content/drive/MyDrive

# If your file is in a subfolder like 'dataset', you can list its contents:
# !ls /content/drive/MyDrive/dataset

# Once you find the correct path and file name, update the 'path_drive' variable below.

 17015652021486224185890399109844.jpg
 17015653050042840439691206155947.jpg
'24.11.6095, muhammad rizquna ali akbat.pdf'
 bitcoin_stock_data.csv
 bukti.jpg
'Colab Notebooks'
'Diberikan snapshot sistem berikut:'$'\n''Hitung isi mat... (1).gsheet'
'Diberikan snapshot sistem berikut:'$'\n''Hitung isi mat... (2).gsheet'
'Diberikan snapshot sistem berikut:'$'\n''Hitung isi mat... (3).gsheet'
'Diberikan snapshot sistem berikut:'$'\n''Hitung isi mat... (4).gsheet'
'Diberikan snapshot sistem berikut:'$'\n''Hitung isi mat... (5).gsheet'
'Diberikan snapshot sistem berikut:'$'\n''Hitung isi mat....gsheet'
'dokumen '
'Dokumen dari logika if03.pdf'
 fg
'FORMULIR PEMBERKASAN_INDO.docx'
'FORMULIR PEMBERKASAN.pdf'
'ijazah lokal Darunnajah. pdf.pdf'
'ijazah negri. pdf.pdf'
 IMG_20240815_180956.jpg
 IMG_20260215_231758.jpg
 IMG_20260215_231822.jpg
 IMG_20260215_233305.jpg
 IMG_20260215_233502.jpg
'KK MAULANA.pdf'
'KRS - UNIVERSITAS AMIKOM Yogyakarta (1).pdf'
'KRS - UNIVERSITAS AMIKOM Yogyakarta.pdf'
'legalisir ..pdf'
'logika informatika.pdf'
'🎴Panorama Color BSG🎴 By Seputar Gcam (Auto).xml'
 SAVE_20240602_214239.jpg
 Screenshot_2025-11-24-17-49-52-776_com.instagram.android.jpg
 Screenshot_2026-05-20-22-38-50-008_com.shopeepay.id.jpg
 Sertifikat
'SIMPLE PRESENT VS PRESENT CONTINUES.doc'
'SK Kelulusan PMB 2024 2025.pdf'
'SKL (1).pdf'
 SKL.pdf
'SURAT KETERANGAN PMB.pdf'
'Surat Lamaran (1).pdf'
'Surat Lamaran.docx'
'Surat Lamaran.pdf'
'SURAT_PERNYATAAN_BEBAS_NARKOBA_2024 (1).docx'
 SURAT_PERNYATAAN_BEBAS_NARKOBA_2024.docx
 SURAT_PERNYATAAN_KEAKTIFAN_MAHASISWA_BARU.docx
'SURAT_PERNYATAAN_KEAKTIFAN_MAHASISWA_BARU(Konflik2024-08-23-17-37-16).docx'
 SURAT_PERNYATAAN_KESANGGUPAN_MENYERAHKAN_IJAZAH_SKHU_2024.docx
'SURAT PERNYATAAN.pdf'
'TEMPLATE LAPORAN UTS ENTREPRENEURSHIP(1).pdf'
'tugas 4 logika.pdf'
'tugas b.inggris1 .pdf'
'tugas b.Inggris tulis 100 kata.pdf'
'tugas kelompok b.inggres.pdf'
'tugas logika 30-10-2024 19.46.pdf'
'tugas logika indi.pdf'
 UTS_PENDIDIKAN_PANCASILA_Muhammad_rizquna_ali_akbar_24.11.6095.pdf

In [55]:
# Membaca dataset langsung dari Google Drive Anda
path_drive = "/content/drive/MyDrive/fg/bitcoin_stock_data.csv"

df_lokal = pd.read_csv(path_drive)
df_lokal.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
5,2014-09-22,399.100006,406.915985,397.130005,402.152008,402.152008,24127600
6,2014-09-23,402.091003,441.557007,396.196014,435.790985,435.790985,40739600
7,2014-09-24,435.897003,436.174011,419.204010,424.393005,424.393005,26268600
8,2014-09-25,424.017014,425.001007,400.802002,404.424988,404.424988,27491400
9,2014-09-26,403.946014,408.324005,395.546997,399.518005,399.518005,22882400

# 3.Dari API Kaggle

In [60]:
# Install dependencies
!pip install kagglehub[pandas-datasets]

import kagglehub
from kagglehub import KaggleDatasetAdapter

# ✓ Urutan benar: adapter → handle → path
df_kaggle = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,       # ← adapter
    "meetnagadia/bitcoin-stock-data-sept-17-2014-august-24-2021", # ← handle
    "BTC-USD.csv"                    # ← nama file dalam dataset
)

print("First 5 records:", df_kaggle.head())

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (26.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.2.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub[pandas-datasets]) (5.29.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.5.20)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

/tmp/ipykernel_3193/306126403.py:8: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_kaggle = kagglehub.load_dataset(

Using Colab cache for faster access to the 'bitcoin-stock-data-sept-17-2014-august-24-2021' dataset.
First 5 records:          Date        Open        High         Low       Close   Adj Close  \
0  2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015
1  2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002
2  2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990
3  2014-09-20  394.673004  423.295990  389.882996  408.903992  408.903992
4  2014-09-21  408.084991  412.425995  393.181000  398.821014  398.821014

     Volume
0  21056800
1  34483200
2  37919700
3  36863600
4  26580100

In [57]:
# Membaca dataset yang diunggah dari lokal
df_lokal = pd.read_csv("bitcoin_stock_data.csv") # Sesuaikan nama file jika berbeda
df_lokal.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
5,2014-09-22,399.100006,406.915985,397.130005,402.152008,402.152008,24127600
6,2014-09-23,402.091003,441.557007,396.196014,435.790985,435.790985,40739600
7,2014-09-24,435.897003,436.174011,419.204010,424.393005,424.393005,26268600
8,2014-09-25,424.017014,425.001007,400.802002,404.424988,404.424988,27491400
9,2014-09-26,403.946014,408.324005,395.546997,399.518005,399.518005,22882400

# 4. Dari Tautan GitHub / Situs Web

In [ ]:
# 4. Upload dataset Bitcoin dari link GITHUB/web
# Ganti URL di bawah ini dengan tautan RAW dari file CSV di GitHub Anda
url_github = "https://raw.githubusercontent.com/username_anda/nama_repo/main/BTC-Hourly.csv"

df_web = pd.read_csv(url_github)
df_web.head(10)